### ISSUE TITLE
Group companies names when they are the same

### ISSUE THREAD

**Issue by coupelon** [gouz/choc#1]
The goal is to clean the format of the companies exported in TSV.
When a talk has multiple speakers, most of the time they are from the same Company. Thus it would be great to detect it and remove duplicates. For instance simplify "Company A, COMPANY A, Company B" in "Company A, Company B"

It might also happen that with several speakers, some don't mention a company. In that case, there can be a floating comma in the string produced. An result such as ", Company A" should simply be "Company A" without the leading comma.

Thanks 😁

**Comment by gouz** [comment]
Feat in version 0.1.6
