### ISSUE TITLE
Suggestion: add a clickable link with render

### ISSUE THREAD

**Issue by ggraveaud** [gouz/choc#4]
Suggestion:

The output "choc -r JSON_FILE" make an actionnable link: 

<img width="542" alt="Capture d’écran 2024-04-20 à 15 53 58" src="https://github.com/gouz/choc/assets/50712344/258eab0e-50ef-46d8-8773-fad41ca8ca17">

**Comment by gouz** [comment]
when you click on the link with the "command" touch, it doesn't work ?

**Comment by ggraveaud** [comment]
yes,  a mac function exists using the "Control" touch.
Topic closed
