### ISSUE TITLE
Suggestion: the command choc without option or json file executes Usage fonction

### ISSUE THREAD

**Issue by ggraveaud** [gouz/choc#5]
the  output of the command choc without option or json file isn't explicit

<img width="510" alt="Capture d’écran 2024-04-20 à 15 56 58" src="https://github.com/gouz/choc/assets/50712344/f9528d3e-1781-4bea-992f-8dbb3e14bac0">

Return the output of the help command should be confortable.

**Comment by gouz** [comment]
fix in 0.1.10
