### ISSUE TITLE
Format Error on my terminal when using choc

### ISSUE THREAD

**Issue by ggraveaud** [gouz/choc#7]
All is on the picture:

<img width="1676" alt="Capture d’écran 2024-04-20 à 11 38 55" src="https://github.com/gouz/choc/assets/50712344/75c2f8dd-b8cd-43a1-80c9-e8c99391f165">

I can share some information about my configuration. Tell me what you need

**Comment by gouz** [comment]
try with -t 70 ?

**Comment by ggraveaud** [comment]
That's works.
pb solved 
<img width="1584" alt="Capture d’écran 2024-04-21 à 12 53 50" src="https://github.com/gouz/choc/assets/50712344/98bd5bf8-dbcf-4cc8-8595-8bb80e807f52">
