### ISSUE TITLE
Suggestion:  Add a "ALL" filter" on the webpage

### ISSUE THREAD

**Issue by ggraveaud** [gouz/choc#8]
On the Webpage, add the filter "All" to make the filter system more understable.
It's empty and not explicit

<img width="803" alt="Capture d’écran 2024-04-20 à 11 40 36" src="https://github.com/gouz/choc/assets/50712344/54796bc5-7dc5-4dfc-baca-34991a62d32d">

**Comment by gouz** [comment]
fix on 0.1.10
